name: Danger

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Get cache dependencies package.json
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install yarn
        run: yarn
      - uses: MeilCli/danger-action@v2
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto approve release
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          AUTHOR: 'dependabot-preview[bot], dependabot[bot], golfzaptw'
